#!/usr/bin/python3
import math
import sys
from cipher import *
from decipher import *

try:
    args = sys.argv
    if len(args) != 4:
        exit(84)
    if args[3] == "0":
        encrypt_message(args[1], args[2])
    elif args[3] == "1":
        decrypt_content(args[1], args[2])
    else:
        assert()
except:
    print("Unknown error occured")
    exit(84)
exit(0)